from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Iterable

from .models import ArtifactSummary, DiscoveryRecord, PackageCatalogEntry
from .paths import BootstrapPaths


def merge_instruction_text(global_agents: Path, repo_agents: Path | None) -> str:
    parts = ["<!-- Generated by agent_bootstrap. Edit canonical AGENTS.md files instead. -->", ""]
    parts.append(global_agents.read_text(encoding="utf-8").rstrip())
    if repo_agents and repo_agents.exists():
        parts.extend(["", repo_agents.read_text(encoding="utf-8").rstrip()])
    return "\n".join(parts).rstrip() + "\n"


def render_workspace_outputs(
    paths: BootstrapPaths,
    workspace: Path,
    enabled_packages: Iterable[str],
    catalog: Dict[str, PackageCatalogEntry],
    discovery: Dict[str, DiscoveryRecord],
) -> None:
    workspace.mkdir(parents=True, exist_ok=True)
    merged = merge_instruction_text(paths.global_agents, workspace / "AGENTS.md")

    (workspace / "CLAUDE.md").write_text(merged, encoding="utf-8")

    copilot_dir = workspace / ".github"
    copilot_dir.mkdir(parents=True, exist_ok=True)
    (copilot_dir / "copilot-instructions.md").write_text(merged, encoding="utf-8")

    cursor_rules_dir = workspace / ".cursor" / "rules"
    cursor_rules_dir.mkdir(parents=True, exist_ok=True)
    (cursor_rules_dir / "bootstrap-skills.mdc").write_text(
        _render_cursor_skills_rule(paths, enabled_packages, discovery), encoding="utf-8"
    )

    cursor_dir = workspace / ".cursor"
    cursor_dir.mkdir(parents=True, exist_ok=True)
    (cursor_dir / "mcp.json").write_text(
        json.dumps(_build_mcp_payload(paths, enabled_packages, catalog), indent=2) + "\n",
        encoding="utf-8",
    )


def render_global_outputs(
    paths: BootstrapPaths, enabled_packages: Iterable[str], catalog: Dict[str, PackageCatalogEntry]
) -> None:
    merged = merge_instruction_text(paths.global_agents, None)
    enabled_packages = sorted(enabled_packages)

    paths.codex_home.mkdir(parents=True, exist_ok=True)
    (paths.codex_home / "AGENTS.md").write_text(merged, encoding="utf-8")
    _sync_codex_skills(paths, enabled_packages)

    paths.claude_home.mkdir(parents=True, exist_ok=True)
    (paths.claude_home / "CLAUDE.md").write_text(merged, encoding="utf-8")
    (paths.claude_home / "AGENTS.md").write_text(merged, encoding="utf-8")

    paths.cursor_home.mkdir(parents=True, exist_ok=True)
    (paths.cursor_home / "mcp.json").write_text(
        json.dumps(_build_mcp_payload(paths, enabled_packages, catalog), indent=2) + "\n",
        encoding="utf-8",
    )


def _render_cursor_skills_rule(
    paths: BootstrapPaths, enabled_packages: Iterable[str], discovery: Dict[str, DiscoveryRecord]
) -> str:
    skill_paths = []
    for package_id in sorted(enabled_packages):
        record = discovery.get(package_id)
        if not record:
            continue
        for skill_name in record.artifact_summary.skills:
            skill_paths.append(str((paths.skills_dir / skill_name / "SKILL.md").resolve()))

    body = "\n".join(f"- {path}" for path in skill_paths) or "- No enabled skills"
    return "\n".join(
        [
            "---",
            "description: Generated bootstrap skill index",
            "alwaysApply: true",
            "---",
            "",
            "# Generated Skill Catalog",
            "",
            body,
            "",
        ]
    )


def _build_mcp_payload(
    paths: BootstrapPaths, enabled_packages: Iterable[str], catalog: Dict[str, PackageCatalogEntry]
) -> dict:
    source = {"mcpServers": {}}
    if paths.mcp_catalog.exists():
        source = json.loads(paths.mcp_catalog.read_text(encoding="utf-8"))

    allowed_keys = set()
    for package_id in enabled_packages:
        entry = catalog.get(package_id)
        if entry:
            allowed_keys.update(entry.mcp_keys)
    filtered = {
        key: value
        for key, value in source.get("mcpServers", {}).items()
        if key in allowed_keys
    }
    return {"mcpServers": filtered}


def _sync_codex_skills(paths: BootstrapPaths, enabled_packages: list[str]) -> None:
    skills_home = paths.codex_home / "skills"
    skills_home.mkdir(parents=True, exist_ok=True)

    wanted = set()
    for package_id in enabled_packages:
        for skill_dir in sorted(paths.skills_dir.glob(f"{package_id}-*")):
            if not (skill_dir / "SKILL.md").exists():
                continue
            wanted.add(skill_dir.name)
            target = skills_home / skill_dir.name
            if target.is_symlink() or target.exists():
                if target.resolve() == skill_dir.resolve():
                    continue
                if target.is_dir() and not target.is_symlink():
                    continue
                target.unlink()
            target.symlink_to(skill_dir.resolve())

    for existing in skills_home.iterdir():
        if existing.name not in wanted and existing.is_symlink():
            existing.unlink()
