from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Iterable

from .models import DiscoveryRecord, PackageCatalogEntry
from .paths import BootstrapPaths

GENERATED_AGENTS_HEADER = "<!-- Generated by agent_bootstrap. Edit canonical AGENTS.md files instead. -->"
WORKSPACE_GITIGNORE_ENTRIES = [
    "CLAUDE.md",
    ".github/copilot-instructions.md",
    ".cursor/rules/bootstrap-skills.mdc",
    ".cursor/mcp.json",
]


def merge_instruction_text(global_agents: Path, repo_agents: Path | None) -> str:
    parts = [GENERATED_AGENTS_HEADER, ""]
    parts.append(global_agents.read_text(encoding="utf-8").rstrip())
    repo_overlay = _read_repo_overlay(repo_agents)
    if repo_overlay:
        parts.extend(["", repo_overlay])
    return "\n".join(parts).rstrip() + "\n"


def render_workspace_outputs(
    paths: BootstrapPaths,
    workspace: Path,
    cursor_packages: Iterable[str],
    catalog: Dict[str, PackageCatalogEntry],
    discovery: Dict[str, DiscoveryRecord],
) -> None:
    workspace.mkdir(parents=True, exist_ok=True)
    _validate_workspace_agents_file(workspace)
    _ensure_workspace_gitignore(workspace)
    merged = merge_instruction_text(paths.global_agents, workspace / "AGENTS.md")

    (workspace / "CLAUDE.md").write_text(merged, encoding="utf-8")

    copilot_dir = workspace / ".github"
    copilot_dir.mkdir(parents=True, exist_ok=True)
    (copilot_dir / "copilot-instructions.md").write_text(merged, encoding="utf-8")

    cursor_rules_dir = workspace / ".cursor" / "rules"
    cursor_rules_dir.mkdir(parents=True, exist_ok=True)
    (cursor_rules_dir / "bootstrap-skills.mdc").write_text(
        _render_cursor_skills_rule(paths, cursor_packages, discovery), encoding="utf-8"
    )

    cursor_dir = workspace / ".cursor"
    cursor_dir.mkdir(parents=True, exist_ok=True)
    (cursor_dir / "mcp.json").write_text(
        json.dumps(_build_mcp_payload(paths, cursor_packages, catalog), indent=2) + "\n",
        encoding="utf-8",
    )


def render_global_outputs(
    paths: BootstrapPaths,
    codex_packages: Iterable[str],
    cursor_packages: Iterable[str],
    catalog: Dict[str, PackageCatalogEntry],
) -> None:
    merged = merge_instruction_text(paths.global_agents, None)
    codex_packages = sorted(codex_packages)
    cursor_packages = sorted(cursor_packages)

    paths.codex_home.mkdir(parents=True, exist_ok=True)
    (paths.codex_home / "AGENTS.md").write_text(merged, encoding="utf-8")
    _sync_codex_skills(paths, codex_packages)

    paths.claude_home.mkdir(parents=True, exist_ok=True)
    (paths.claude_home / "CLAUDE.md").write_text(merged, encoding="utf-8")
    (paths.claude_home / "AGENTS.md").write_text(merged, encoding="utf-8")

    paths.cursor_home.mkdir(parents=True, exist_ok=True)
    (paths.cursor_home / "mcp.json").write_text(
        json.dumps(_build_mcp_payload(paths, cursor_packages, catalog), indent=2) + "\n",
        encoding="utf-8",
    )


def _agents_skills_home() -> Path:
    return Path.home() / ".agents" / "skills"


def _project_skills_lock(paths: BootstrapPaths) -> Path:
    return paths.root / "skills-lock.json"


def _global_skills_lock() -> Path:
    return Path.home() / ".agents" / ".skill-lock.json"


def _skill_names_from_lock(lock_file: Path) -> list[str]:
    if not lock_file.exists():
        return []

    data = json.loads(lock_file.read_text(encoding="utf-8"))
    skills = data.get("skills")
    if isinstance(skills, dict):
        return sorted(skills.keys())

    sources = data.get("sources")
    if isinstance(sources, list):
        names: list[str] = []
        for item in sources:
            if isinstance(item, dict) and "name" in item:
                names.append(str(item["name"]))
            elif isinstance(item, str):
                names.append(item)
        return sorted(names)

    return []


def _installed_skill_dirs(paths: BootstrapPaths) -> list[Path]:
    agents_home = _agents_skills_home()
    lock_names = _skill_names_from_lock(_project_skills_lock(paths))
    if not lock_names:
        lock_names = _skill_names_from_lock(_global_skills_lock())

    dirs: list[Path] = []
    if lock_names:
        for name in lock_names:
            skill_dir = agents_home / name
            if (skill_dir / "SKILL.md").exists():
                dirs.append(skill_dir.resolve())
        return dirs

    if not agents_home.exists():
        return dirs

    for skill_dir in sorted(agents_home.iterdir()):
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
            dirs.append(skill_dir.resolve())
    return dirs


def _render_cursor_skills_rule(
    paths: BootstrapPaths, enabled_packages: Iterable[str], discovery: Dict[str, DiscoveryRecord]
) -> str:
    del enabled_packages, discovery

    skill_paths = [
        str(skill_dir / "SKILL.md")
        for skill_dir in _installed_skill_dirs(paths)
    ]

    body = "\n".join(f"- {path}" for path in skill_paths) or "- No installed skills"
    return "\n".join(
        [
            "---",
            "description: Generated bootstrap skill index",
            "alwaysApply: true",
            "---",
            "",
            "# Generated Skill Catalog",
            "",
            "Installed skills are resolved from skills-lock.json and ~/.agents/skills/.",
            "",
            body,
            "",
        ]
    )


def _build_mcp_payload(
    paths: BootstrapPaths, enabled_packages: Iterable[str], catalog: Dict[str, PackageCatalogEntry]
) -> dict:
    source = {"mcpServers": {}}
    if paths.mcp_catalog.exists():
        source = json.loads(paths.mcp_catalog.read_text(encoding="utf-8"))

    allowed_keys = set()
    for package_id in enabled_packages:
        entry = catalog.get(package_id)
        if entry:
            allowed_keys.update(entry.mcp_keys)
    filtered = {
        key: value
        for key, value in source.get("mcpServers", {}).items()
        if key in allowed_keys
    }
    return {"mcpServers": filtered}


def _sync_codex_skills(paths: BootstrapPaths, enabled_packages: list[str]) -> None:
    del enabled_packages

    skills_home = paths.codex_home / "skills"
    skills_home.mkdir(parents=True, exist_ok=True)

    wanted = {skill_dir.name for skill_dir in _installed_skill_dirs(paths)}
    agents_home = _agents_skills_home()

    for skill_name in sorted(wanted):
        source = agents_home / skill_name
        if not (source / "SKILL.md").exists():
            continue
        target = skills_home / skill_name
        if target.is_symlink() or target.exists():
            if target.resolve() == source.resolve():
                continue
            if target.is_dir() and not target.is_symlink():
                continue
            target.unlink()
        target.symlink_to(source.resolve())

    for existing in skills_home.iterdir():
        if existing.name not in wanted and existing.is_symlink():
            existing.unlink()


def _ensure_workspace_gitignore(workspace: Path) -> None:
    gitignore = workspace / ".gitignore"
    lines: list[str] = []
    if gitignore.exists():
        lines = gitignore.read_text(encoding="utf-8").splitlines()

    filtered_lines: list[str] = []
    skip_old_block = False
    for line in lines:
        if line == "# agent_bootstrap generated outputs":
            skip_old_block = True
            continue
        if skip_old_block:
            if line == "# /agent_bootstrap generated outputs":
                skip_old_block = False
            continue
        filtered_lines.append(line)

    existing_entries = set(filtered_lines)
    updated_lines = list(filtered_lines)
    if updated_lines and updated_lines[-1] != "":
        updated_lines.append("")

    for entry in WORKSPACE_GITIGNORE_ENTRIES:
        if entry not in existing_entries:
            updated_lines.append(entry)

    while len(updated_lines) > 1 and updated_lines[-1] == "" and updated_lines[-2] == "":
        updated_lines.pop()

    gitignore.write_text("\n".join(updated_lines).rstrip() + "\n", encoding="utf-8")


def _read_repo_overlay(repo_agents: Path | None) -> str | None:
    if repo_agents is None or not repo_agents.exists():
        return None
    content = repo_agents.read_text(encoding="utf-8").rstrip()
    return content or None


def _validate_workspace_agents_file(workspace: Path) -> None:
    agents_file = workspace / "AGENTS.md"
    if agents_file.is_symlink():
        target = agents_file.resolve()
        raise ValueError(
            "Workspace AGENTS.md must be a real authored file, not a symlink. "
            f"Found symlink: {agents_file} -> {target}. "
            "Restore the repo-specific AGENTS.md as a regular file, then rerun agent_bootstrap."
        )
    if agents_file.exists():
        content = agents_file.read_text(encoding="utf-8")
        if content.startswith(GENERATED_AGENTS_HEADER):
            raise ValueError(
                "Workspace AGENTS.md looks generated instead of authored. "
                f"Found generated content in {agents_file}. "
                "Restore the repo-specific AGENTS.md as a normal authored file, then rerun agent_bootstrap."
            )
