from __future__ import annotations

import json
from pathlib import Path

from .paths import BootstrapPaths

GENERATED_AGENTS_HEADER = "<!-- Generated by agent_bootstrap. Edit canonical AGENTS.md files instead. -->"


def merge_instruction_text(global_agents: Path, repo_agents: Path | None) -> str:
    parts = [GENERATED_AGENTS_HEADER, ""]
    parts.append(global_agents.read_text(encoding="utf-8").rstrip())
    repo_overlay = _read_repo_overlay(repo_agents)
    if repo_overlay:
        parts.extend(["", repo_overlay])
    return "\n".join(parts).rstrip() + "\n"


def render_global_outputs(paths: BootstrapPaths) -> None:
    """Render global AGENTS.md outputs and Codex skill symlinks.

    MCP writing from catalog is archived — see archive/mcp/ and archive/catalog/.
    """
    merged = merge_instruction_text(paths.global_agents, None)

    paths.codex_home.mkdir(parents=True, exist_ok=True)
    (paths.codex_home / "AGENTS.md").write_text(merged, encoding="utf-8")
    _sync_codex_skills(paths)

    paths.claude_home.mkdir(parents=True, exist_ok=True)
    (paths.claude_home / "CLAUDE.md").write_text(merged, encoding="utf-8")
    (paths.claude_home / "AGENTS.md").write_text(merged, encoding="utf-8")


def _agents_skills_home() -> Path:
    return Path.home() / ".agents" / "skills"


def _project_skills_lock(paths: BootstrapPaths) -> Path:
    return paths.root / "skills-lock.json"


def _global_skills_lock() -> Path:
    return Path.home() / ".agents" / ".skill-lock.json"


def _skill_names_from_lock(lock_file: Path) -> list[str]:
    if not lock_file.exists():
        return []

    data = json.loads(lock_file.read_text(encoding="utf-8"))
    skills = data.get("skills")
    if isinstance(skills, dict):
        return sorted(skills.keys())

    sources = data.get("sources")
    if isinstance(sources, list):
        names: list[str] = []
        for item in sources:
            if isinstance(item, dict) and "name" in item:
                names.append(str(item["name"]))
            elif isinstance(item, str):
                names.append(item)
        return sorted(names)

    return []


def _installed_skill_dirs(paths: BootstrapPaths) -> list[Path]:
    agents_home = _agents_skills_home()
    lock_names = _skill_names_from_lock(_project_skills_lock(paths))
    if not lock_names:
        lock_names = _skill_names_from_lock(_global_skills_lock())

    dirs: list[Path] = []
    if lock_names:
        for name in lock_names:
            skill_dir = agents_home / name
            if (skill_dir / "SKILL.md").exists():
                dirs.append(skill_dir.resolve())
        return dirs

    if not agents_home.exists():
        return dirs

    for skill_dir in sorted(agents_home.iterdir()):
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
            dirs.append(skill_dir.resolve())
    return dirs


def _sync_codex_skills(paths: BootstrapPaths) -> None:
    skills_home = paths.codex_home / "skills"
    skills_home.mkdir(parents=True, exist_ok=True)

    wanted = {skill_dir.name for skill_dir in _installed_skill_dirs(paths)}
    agents_home = _agents_skills_home()

    for skill_name in sorted(wanted):
        source = agents_home / skill_name
        if not (source / "SKILL.md").exists():
            continue
        target = skills_home / skill_name
        if target.is_symlink() or target.exists():
            if target.resolve() == source.resolve():
                continue
            if target.is_dir() and not target.is_symlink():
                continue
            target.unlink()
        target.symlink_to(source.resolve())

    for existing in skills_home.iterdir():
        if existing.name not in wanted and existing.is_symlink():
            existing.unlink()


def _read_repo_overlay(repo_agents: Path | None) -> str | None:
    if repo_agents is None or not repo_agents.exists():
        return None
    content = repo_agents.read_text(encoding="utf-8").rstrip()
    return content or None
