from __future__ import annotations

import json
from pathlib import Path

from .claude_bridge import run_claude_bridge
from .paths import BootstrapPaths

GENERATED_AGENTS_HEADER = "<!-- Generated by agent_bootstrap. Edit canonical AGENTS.md files instead. -->"


def merge_instruction_text(global_agents: Path, repo_agents: Path | None) -> str:
    parts = [GENERATED_AGENTS_HEADER, ""]
    parts.append(global_agents.read_text(encoding="utf-8").rstrip())
    repo_overlay = _read_repo_overlay(repo_agents)
    if repo_overlay:
        parts.extend(["", repo_overlay])
    return "\n".join(parts).rstrip() + "\n"


def render_global_outputs(paths: BootstrapPaths) -> None:
    """Render global AGENTS.md outputs and Codex skill symlinks.

    MCP writing from catalog is archived — see archive/mcp/ and archive/catalog/.
    """
    merged = merge_instruction_text(paths.global_agents, None)

    paths.codex_home.mkdir(parents=True, exist_ok=True)
    (paths.codex_home / "AGENTS.md").write_text(merged, encoding="utf-8")
    _sync_codex_skills(paths)

    paths.claude_home.mkdir(parents=True, exist_ok=True)
    (paths.claude_home / "CLAUDE.md").write_text(merged, encoding="utf-8")
    (paths.claude_home / "AGENTS.md").write_text(merged, encoding="utf-8")
    run_claude_bridge(paths)


def _project_skills_lock(paths: BootstrapPaths) -> Path:
    return paths.root / "skills-lock.json"


def _skill_names_from_lock(lock_file: Path) -> list[str] | None:
    """Return lock skill names, or None when an existing lock is malformed."""
    if not lock_file.exists():
        return []

    try:
        data = json.loads(lock_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    skills = data.get("skills")
    if isinstance(skills, dict):
        return sorted(skills.keys())

    sources = data.get("sources")
    if isinstance(sources, list):
        names: list[str] = []
        for item in sources:
            if isinstance(item, dict) and "name" in item:
                names.append(str(item["name"]))
            elif isinstance(item, str):
                names.append(item)
        return sorted(names)

    return []


def managed_skill_names(paths: BootstrapPaths) -> list[str]:
    lock_names = _skill_names_from_lock(_project_skills_lock(paths))
    # The project lock is only a stub for global installs; a malformed stub
    # must not prevent a valid authoritative global lock from being used.
    if lock_names is None:
        lock_names = []
    if not lock_names:
        lock_names = _skill_names_from_lock(paths.global_skill_lock)
    return lock_names or []


def installed_skill_dirs(paths: BootstrapPaths) -> list[Path]:
    """Return every valid local skill directory, regardless of lock provenance."""
    agents_home = paths.agents_skills_home
    if not agents_home.exists():
        return []

    dirs: list[Path] = []
    for skill_dir in sorted(agents_home.iterdir()):
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
            dirs.append(skill_dir.resolve())
    return dirs


def _sync_codex_skills(paths: BootstrapPaths) -> None:
    skills_home = paths.codex_home / "skills"
    skills_home.mkdir(parents=True, exist_ok=True)

    wanted = {skill_dir.name for skill_dir in installed_skill_dirs(paths)}
    agents_home = paths.agents_skills_home

    for skill_name in sorted(wanted):
        source = agents_home / skill_name
        if not (source / "SKILL.md").exists():
            continue
        target = skills_home / skill_name
        if target.is_symlink() or target.exists():
            if target.resolve() == source.resolve():
                continue
            # A different path belongs to the user or another installer. Never
            # replace it merely because this source is currently lock-managed.
            continue
        target.symlink_to(source.resolve())


def _read_repo_overlay(repo_agents: Path | None) -> str | None:
    if repo_agents is None or not repo_agents.exists():
        return None
    content = repo_agents.read_text(encoding="utf-8").rstrip()
    return content or None
