from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Mapping, Sequence


MANAGED_BEGIN = "<!-- BEGIN AGENTBOT MANAGED BASELINE -->"
MANAGED_END = "<!-- END AGENTBOT MANAGED BASELINE -->"
GENERATED_HEADER = "<!-- Generated by Agentbot. Edit AGENTS.md, not this file. -->"
PROJECT_HEADING = re.compile(r"(?m)^## Project[ \t]*(?:\n|$)")

OUTPUT_PATHS = {
    "agents": "AGENTS.md",
    "claude": "CLAUDE.md",
    "copilot": ".github/copilot-instructions.md",
    "cursor": ".cursor/rules/agentbot-policy.mdc",
}
WORKSPACE_TARGETS = frozenset(OUTPUT_PATHS)
LEGACY_CLAUDE_CONTENT = (
    "IMPORTANT: Read and follow all instructions in AGENTS.md before starting any task.\n\n"
    "@AGENTS.md\n"
)


@dataclass(frozen=True)
class RenderAction:
    relative_path: str
    kind: Literal["create", "update", "unchanged", "conflict"]
    content: str | None
    detail: str


@dataclass(frozen=True)
class WorkspaceRenderPlan:
    actions: tuple[RenderAction, ...]
    policy_mode: Literal["managed", "custom"]

    def action_for(self, relative_path: str) -> RenderAction:
        for action in self.actions:
            if action.relative_path == relative_path:
                return action
        raise KeyError(relative_path)

    def paths(self) -> tuple[str, ...]:
        return tuple(action.relative_path for action in self.actions)


def build_workspace_render_plan(
    base_template: str,
    existing_files: Mapping[str, str],
    selected_targets: Sequence[str],
) -> WorkspaceRenderPlan:
    _validate_existing_paths(existing_files)
    targets = _normalize_targets(selected_targets)
    base_prefix, base_project = split_base_template(base_template)

    existing_agents = existing_files.get("AGENTS.md")
    policy_mode: Literal["managed", "custom"]
    malformed_agents_detail: str | None = None
    try:
        resolved_agents, policy_mode = resolve_agents_policy(
            base_template,
            existing_agents,
        )
    except ValueError as error:
        resolved_agents = existing_agents or ""
        policy_mode = "custom"
        malformed_agents_detail = str(error)

    actions: list[RenderAction] = []
    agents_path = OUTPUT_PATHS["agents"]
    if malformed_agents_detail is not None:
        actions.append(
            RenderAction(
                relative_path=agents_path,
                kind="conflict",
                content=None,
                detail=malformed_agents_detail,
            )
        )
    else:
        actions.append(
            _content_action(
                agents_path,
                existing_agents,
                resolved_agents,
                create_detail="create managed AGENTS.md",
                update_detail="refresh managed AGENTS.md baseline",
                unchanged_detail="managed AGENTS.md is current",
                custom_detail="preserve custom AGENTS.md",
                custom=(policy_mode == "custom"),
            )
        )

    renderers = {
        "claude": lambda: render_claude(),
        "copilot": lambda: render_copilot(resolved_agents),
        "cursor": lambda: render_cursor(resolved_agents),
    }
    for target in ("claude", "copilot", "cursor"):
        if target not in targets:
            continue
        relative_path = OUTPUT_PATHS[target]
        desired = renderers[target]()
        actions.append(
            _compatibility_action(
                relative_path,
                existing_files.get(relative_path),
                desired,
                target=target,
            )
        )

    return WorkspaceRenderPlan(actions=tuple(actions), policy_mode=policy_mode)


def split_base_template(template: str) -> tuple[str, str]:
    match = PROJECT_HEADING.search(template)
    if match is None:
        raise ValueError("base AGENTS.md must contain a ## Project heading")
    prefix = template[: match.start()]
    project = template[match.start() :].lstrip("\n")
    return prefix, project


def render_managed_agents(base_prefix: str, project_section: str) -> str:
    return (
        f"{MANAGED_BEGIN}\n\n"
        f"{base_prefix.rstrip()}\n\n"
        f"{MANAGED_END}\n\n"
        f"{project_section.rstrip()}\n"
    )


def resolve_agents_policy(
    base_template: str,
    existing_content: str | None,
) -> tuple[str, Literal["managed", "custom"]]:
    base_prefix, base_project = split_base_template(base_template)
    if existing_content is None:
        return render_managed_agents(base_prefix, base_project), "managed"

    has_marker = MANAGED_BEGIN in existing_content or MANAGED_END in existing_content
    if has_marker:
        if (
            existing_content.count(MANAGED_BEGIN) != 1
            or existing_content.count(MANAGED_END) != 1
        ):
            raise ValueError("AGENTS.md has an invalid Agentbot marker pair")
        begin = existing_content.index(MANAGED_BEGIN)
        end = existing_content.index(MANAGED_END)
        if begin > end:
            raise ValueError("AGENTS.md has an out-of-order Agentbot marker pair")
        suffix_start = end + len(MANAGED_END)
        suffix = existing_content[suffix_start:]
        if PROJECT_HEADING.search(suffix) is None:
            raise ValueError("managed AGENTS.md must contain a ## Project section after markers")
        replacement = (
            f"{MANAGED_BEGIN}\n\n"
            f"{base_prefix.rstrip()}\n\n"
            f"{MANAGED_END}"
        )
        return (
            existing_content[:begin] + replacement + existing_content[suffix_start:],
            "managed",
        )

    base_match = PROJECT_HEADING.search(base_template)
    existing_match = PROJECT_HEADING.search(existing_content)
    if (
        base_match is not None
        and existing_match is not None
        and existing_content[: existing_match.start()]
        == base_template[: base_match.start()]
    ):
        project_section = existing_content[existing_match.start() :].lstrip("\n")
        return render_managed_agents(base_prefix, project_section), "managed"

    return existing_content, "custom"


def render_claude() -> str:
    return (
        f"{GENERATED_HEADER}\n\n"
        "IMPORTANT: Read and follow all instructions in AGENTS.md before starting any task.\n\n"
        "@AGENTS.md\n"
    )


def render_copilot(resolved_agents: str) -> str:
    return f"{GENERATED_HEADER}\n\n# Repository instructions\n\n{resolved_agents}"


def render_cursor(resolved_agents: str) -> str:
    return (
        "---\n"
        "description: Agentbot-managed repository instructions\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{GENERATED_HEADER}\n\n"
        f"{resolved_agents}"
    )


def apply_workspace_render_plan(
    root: Path,
    plan: WorkspaceRenderPlan,
) -> tuple[RenderAction, ...]:
    conflicts = [action for action in plan.actions if action.kind == "conflict"]
    if conflicts:
        paths = ", ".join(action.relative_path for action in conflicts)
        raise ValueError(f"cannot apply workspace render plan with conflicts: {paths}")

    writes = [action for action in plan.actions if action.kind in {"create", "update"}]
    _validate_write_locations(root, writes)
    applied: list[RenderAction] = []
    for action in writes:
        destination = root / action.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        fd, temporary_name = tempfile.mkstemp(
            prefix=f".{destination.name}.agentbot-",
            dir=destination.parent,
        )
        temporary = Path(temporary_name)
        try:
            os.fchmod(fd, 0o644)
            with os.fdopen(fd, "w", encoding="utf-8", newline="") as stream:
                stream.write(action.content or "")
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, destination)
            applied.append(action)
        finally:
            if temporary.exists():
                temporary.unlink()

    return tuple(applied)


def _normalize_targets(selected_targets: Sequence[str]) -> tuple[str, ...]:
    targets: list[str] = []
    for target in selected_targets:
        normalized = "agents" if target == "codex" else target
        if normalized not in WORKSPACE_TARGETS:
            raise ValueError(f"unsupported workspace target: {target}")
        if normalized in targets:
            raise ValueError(f"duplicate workspace target: {normalized}")
        targets.append(normalized)
    if "agents" not in targets:
        targets.insert(0, "agents")
    return tuple(target for target in OUTPUT_PATHS if target in targets)


def _validate_existing_paths(existing_files: Mapping[str, str]) -> None:
    allowed = set(OUTPUT_PATHS.values())
    for path in existing_files:
        if path not in allowed:
            raise ValueError(f"unsupported workspace target: {path}")


def _content_action(
    relative_path: str,
    existing: str | None,
    desired: str,
    *,
    create_detail: str,
    update_detail: str,
    unchanged_detail: str,
    custom_detail: str,
    custom: bool,
) -> RenderAction:
    if custom:
        return RenderAction(relative_path, "unchanged", existing, custom_detail)
    if existing is None:
        return RenderAction(relative_path, "create", desired, create_detail)
    if existing == desired:
        return RenderAction(relative_path, "unchanged", desired, unchanged_detail)
    return RenderAction(relative_path, "update", desired, update_detail)


def _compatibility_action(
    relative_path: str,
    existing: str | None,
    desired: str,
    *,
    target: str,
) -> RenderAction:
    if existing is None:
        return RenderAction(relative_path, "create", desired, f"create {target} output")
    if not _is_agentbot_owned_compatibility(relative_path, existing):
        return RenderAction(
            relative_path,
            "conflict",
            None,
            f"existing {target} file is not marked as Agentbot-managed",
        )
    if existing == desired:
        return RenderAction(relative_path, "unchanged", desired, f"{target} output is current")
    return RenderAction(relative_path, "update", desired, f"refresh {target} output")


def _is_agentbot_owned_compatibility(relative_path: str, content: str) -> bool:
    if GENERATED_HEADER in content:
        return True
    return relative_path == OUTPUT_PATHS["claude"] and content == LEGACY_CLAUDE_CONTENT


def _validate_write_locations(root: Path, actions: Sequence[RenderAction]) -> None:
    root = root.resolve()
    if not root.is_dir():
        raise ValueError(f"workspace root is not a directory: {root}")
    for action in actions:
        destination = root / action.relative_path
        current = root
        for part in Path(action.relative_path).parts[:-1]:
            current /= part
            if current.exists() and (current.is_symlink() or not current.is_dir()):
                raise ValueError(f"workspace output parent is unsafe: {current}")
        if destination.is_symlink():
            raise ValueError(f"workspace output is a symlink: {destination}")
